---
- name: Prepare server for deployment
  hosts: web_server_instances
  gather_facts: true
  
  vars:
    ansible_become: yes
    ansible_become_method: sudo

  pre_tasks:
    - name: Show connection info
      debug:
        msg: "Connecting to {{ ansible_host }} as {{ ansible_user }}"

    - name: Test SSH connection
      ping:

  roles:
    - prepare_server